spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security_sangeng?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always